#include "styles.h"

#include <QApplication>
#include <QFontDatabase>
#include <QDebug>
#include <QLayout>

Styles::Styles(QObject *parent) : QObject(parent)
{
    qApp->setStyleSheet(""
        "QWidget {"
            "background-color: rgba(70, 70, 70, 0.8);"
            "border: 1px solid rgba(50, 50, 50, 0.8);"
            "color: #cccccc;"
            "font-family: Monospace;"
        "}"
        "QVBoxLayout, QHBoxLayout, QGridLayout, QSplitter, QTabWidget {"
            "border: 0;"
            "margin: 0;"
            "padding: 0;"
        "}"
        "QLineEdit { "
            "background-color: rgba(101, 101, 101, 0.8);"
            "color: #cccccc;"
            "border: 1px solid rgba(50, 50, 50, 0.8);"
            "border-radius: 4px;"
        "}"
        "QPushButton { "
            "background-color: rgba(101, 101, 101, 0.8);"
            "color: #cccccc;"
            "border: 1px solid rgba(50, 50, 50, 0.8);"
            "border-radius: 4px; "
        "}"
		"QPushButton:clicked, QPushButton:pressed, QPushButton:checked { "
            "background-color: rgba(55, 55, 55, 0.8);"
            "color: #cccccc;"
            "border: 1px solid rgba(50, 50, 50, 0.8);"
            "border-radius: 4px; "
        "}"
        "QTabBar {"
            "border: 0;"
            "padding: 2px 0 0 0;"
        "}"
        "QSlider::groove:horizontal {"
            "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #515151, stop:1 #646464);"
            "border: 1px solid #444444;"
            "height: 8px;"
        "}"
        "QSlider::handle:horizontal {"
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);"
            "border: 1px solid #5c5c5c;"
            "width: 18px;"
            "margin: -2px 0;"
            "border-radius: 3px;"
        "}");
}
